name: "envmon"
services:
  api:
    build:
      context: provider
      dockerfile: Dockerfile.prod
    image: envmon-api
    restart: unless-stopped
    ports:
      - 0.0.0.0:8080:8080
      - 3080:3080
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    container_name: backend
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: envmon-db

  web:
    build:
      context: web
      dockerfile: Dockerfile.prod
    ports:
      - 0.0.0.0:3000:3000
    container_name: envmon-web
    depends_on:
      - api
