[build]
cmd = "go build -o ./build/main cmd/main.go cmd/api.go cmd/datasync.go cmd/service.go cmd/logging.go cmd/db.go" 
bin = "./build/main"
include_ext = ["go"]
exclude_dir = ["build", "vendor"]

[log]
level = "debug"
