name: "esp32-env-monitor"
services:
  api:
    build: .
    image: api:dev
    restart: always
    ports:
      - 0.0.0.0:8080:8080
    environment:
      - DATABASE_PATH=${DATABASE_PATH}
    container_name: esp32-env-monitor
    volumes:
      - ./data.db:/usr/app/data.db
      - ./cmd:/usr/app/cmd/
