export enum GraphInterval {
  ONE_DAY = "ONE_DAY",
  // ONE_HOUR = "ONE_HOUR",
  HALF_HOUR = "HALF_HOUR",
  // TWELVE_HOURS = "TWELVE_HOURS",
  // SIX_HOURS = "SIX_HOURS",
  ONE_WEEK = "ONE_WEEK",
  TWO_WEEKS = "TWO_WEEKS",
  ONE_MONTH = "ONE_MONTH",
  // THREE_MONTHS = "THREE_MONTHS",
}
