FROM node:22-alpine

RUN npm i -g pnpm

WORKDIR /app
COPY package*.json pnpm-lock.yaml ./
COPY tsconfig.json ./
COPY postcss.config.js ./
COPY tailwind.config.ts ./
RUN pnpm install


EXPOSE 3000
CMD pnpm dev
